version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
     interval: "monthly" # Options: "daily", "weekly", "monthly"

# Optional: Group all action updates into ONE PR to avoid spam
    groups:
      github-actions-deps:
        patterns:
         - "*"
