---
title: "Data Information"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please find information regarding data extracted for each species and data file formats.

## Location of reports

All reports were downloaded from 

* [Stock Assessment Review Index (SARI)](https://www.nefsc.noaa.gov/saw/reviews_report_options.php)
* [Stock Assessment Support Information (SASINF)](https://www.nefsc.noaa.gov/saw/sasi/sasi_report_options.php)

## Input file formats

All pdf files should have the same format.

YEAR_SPECIESNAME_LOCATION_REPORTNAME.pdf (Note: 3 underscores) 

eg. 2017_mackerel_GOM-GB-MA_SARC64-18-06.pdf


* LOCATION defines the location where SPECIESNAME is harvested/sampled (eg, GB, GOM, EastGB, GB-GOM, etc).
Use hyphens to separate acronyms/words in LOCATION

* REPORTNAME defines the source report of the pdf.

Do not use additional underscores. Underscores will be used to split the pdf name if necessary.


## Output

Column names in all tables vary across species. No consistency


## Herring 

Biomass, landings, discards extracted
Need to determin how to combine (although discards seem pretty small to me, maybe worth ignoring)

