name: send email test

on:
  workflow_dispatch:

jobs:
  sending-email:
    runs-on: ubuntu-latest

    steps:

      - name: Send email
        uses: dawidd6/action-send-mail@v18

        with:
          server_address: smtp.gmail.com
          server_port: 465

          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          subject: Github Actions job result
          to: andrew.beet@noaa.gov

          from: 'Luke Skywalker <user@example.com>'
          envelope_from: ${{ secrets.MAIL_USERNAME }}

          body: ${{ github.repository }} updated data!
